service: concurrency

provider:
  timeout: 60
  memorySize: 1024
  profile: concurrency
  name: aws
  stage: staging
  region: us-east-1
  runtime: nodejs14.x
  endpointType: regional
  versionFunctions: false
  tracing:
    lambda: false
    apiGateway: false
  logRetentionInDays: 1
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

constructs:
  requests:
    type: queue
    worker:
      handler: lib/process/handler.handler
      timeout: 60

plugins:
  - serverless-lift
