service: concurrency

provider:
  timeout: 60
  memorySize: 1024
  profile: concurrency
  name: aws
  stage: ${env:ENVIRONMENT}
  region: ${env:AWS_DEFAULT_REGION}
  runtime: nodejs14.x
  endpointType: regional
  versionFunctions: false
  tracing:
    lambda: false
    apiGateway: false
  logRetentionInDays: 3
  environment:
    ENVIRONMENT: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'xray:PutTraceSegments'
            - 'xray:PutTelemetryRecords'
          Resource:
            - '*'

functions:
  process:
    handler: lib/process/handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:494014222317:requests
          batchSize: 1
